### ISSUE TITLE
Unable to delete tasks (JS error) on Egde browser

### ISSUE THREAD

**Issue by zamostny** [MorganJay/Synchronous-ToDo-App#2]
I suddenly lost the ability to delete tasks and after checking the console in Edge, I see this error:

`Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLButtonElement.delItem (script2.js:127:26)`

The only changes I have made to the app were purely in CSS (color, positioning, etc). Files attached for your review. 

[TaskApp.zip](https://github.com/MorganJay/Persistent-ToDo-App/files/10456563/TaskApp.zip)

**Comment by zamostny** [comment]
Just to add more info. I have tried a fresh download of your app from GitHub and confirmed I cannot delete tasks still. 

I have cleared browser cache and restarted. Not sure what is causing the browser to stop deleting tasks.

**Comment by MorganJay** [comment]
Hey there, can you try using the published app? 

The link is in the README. 

I tried it out and deleting tasks works as expected.

**Comment by zamostny** [comment]
I'm trying it now and it's not working in Edge browser.

**Comment by MorganJay** [comment]
Oh, I see the error now. I'll check it out later. You can raise a PR to address the issue tho

**Comment by zamostny** [comment]
Any update on the delete bug? I've tried other browsers with the same issue.

**Comment by MorganJay** [comment]
I've pushed a fix, cheers 🚀
